# build and publish package to PyPI on release

name: Publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Build
        run: poetry build
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish-pypi:
    runs-on: ubuntu-latest
    needs: build
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Load artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  attach-to-release:
    runs-on: ubuntu-latest
    needs: build
    environment: release
    steps:
      - name: Load artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Upload dist files to release
        run: |
          for file in dist/*; do
            gh release upload ${{ github.ref }} $file
          done
